### PR TITLE
Support recent libsigrok changes

### PR DESCRIPTION
**Pull request by gtrentalancia**
**1. The vertical scale setting is improperly named "vdiv" and as
    such it creates a great deal of confusion especially in new
    users and developers because it is easily mistaken with
    "num_vdiv" which is the number of vertical divisions !**

This pulseview patch is required by a recent libsigrok change:

https://github.com/sigrokproject/libsigrok/pull/17/commits/fc685341b2a32708f9e098e57a51d6bde894c6f6?
---
 pv/binding/device.cpp |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

------------------------------------------------------------------------------------------------------------------------------------

**2. Initial support for the FFT functionality recently introduced
    in libsigrok**

This pulseview patch is required by a recent libsigrok change:

https://github.com/sigrokproject/libsigrok/pull/17/commits/8d6d70eac5fad6b4e4f99378ea04baf921b707b7?
---
pv/session.cpp |    1 +
1 file changed, 1 insertion(+)

------------------------------------------------------------------------------------------------------------------------------------

**3. Do not crash on SCPI commands failure during config_set() but retry**

This pulseview patch needs the following recent libsigrok change:

https://github.com/sigrokproject/libsigrok/pull/17/commits/ed02b51299563e788deb6c9c01dc1baafa3b5e59?
---
 pv/binding/device.cpp   |    5 +++--
 pv/toolbars/mainbar.cpp |   12 ++++++++----
 2 files changed, 11 insertions(+), 6 deletions(-)

------------------------------------------------------------------------------------------------------------------------------------

**4. Do not attempt to set the Sample Rate to zero**

---
 pv/toolbars/mainbar.cpp |    2 ++
 1 file changed, 2 insertions(+)

### CODE REVIEW

**Comment by depili** [comment]
Sorry it  has been a long while without anyone looking into this. Do you still want to work on this and do you still think any of the proposed changes are relevant and not yet resolved via other changes in past 4 years?

**Comment by gtrentalancia** [comment]
There were a lot of proposed changes that have not been merged. The official fork description is available here https://sigrok-fork.trentalancia.com

Feel free to take a look at missing changes, some of them are particularly interesting, for example the FFT support.

Then let me know if anybody is interested in merging them.

**Comment by depili** [comment]
There are multiple issues about merging any of this:
- There are merge conflicts
- It is unclear why some of that stuff is relevant
- You have changed some of the established device names
- You don't seem to provide a commit log to see the change messages and
changes to check code quality
- You are proposing a massive change set as one unit instead of breaking
it to several independent changes

As it currently is this work cannot be considered for merging and will
need much work still.

**Comment by gtrentalancia** [comment]
As already explained, the whole original patchset is explained at https://sigrok-fork.trentalancia.com

It is pretty obvious that when stuff is not merged integrally straightaway, then merge conflicts arise. Fortunately, merge conflicts are very often easy to resolve.

The whole patchset was involving libsigrok + sigrok-cli + pulseview changes: some are interdependent for obvious reasons (for example the FFT functionality).

The first thing I need to know is which of the new functionalities or bug-fixes, as reported in my personal website are you interested in merging ?

In the meanwhile, I will try to answer some of your questions:

- the naming is not generally particularly important or relevant: in any case, as far as I remember, the Hameg company does not exist anymore as it has been merged or bought by Rhode&Schwarz, therefore the name change has pretty obvious reasons;

- as for the relevance, of each patch, please see their detailed description and it should be clear, as long as you are familiar with the oscilloscope functionality

- it's not a massive changeset, possibly medium or big, but in any case it's made of 93+6+4=103 small patches: obviously not all of them are independent of each other

Many patches have already been merged. I do not remember which patches have been left out. Anyway, if you tell me which changes are of interest to you, I can try to resolve the merge conflicts.

**Comment by depili** [comment]
The page you are refering isn't usable as documentation. Also I asked you
if any of the changes in this PR are still relevant and if you want to
work towards getting them merged. I have no time to dwell into a single
tarball containing untold undocumented changes.

Given this PR is old, has merge conflicts and contains multiple unrelated
changes in a single PR and doesn't give the reasoning about the changes I
will probably close this. Feel free to open single requests for individual
items that are still needed. Bear in mind the coding style and VCS commit
message style guides of the project for any such future requests.

**Comment by gtrentalancia** [comment]
I didn't mean that the page could be used as "documentation" or complete commit description. However each patch has a very descriptive title that highlighs its functionality or purpose.

I did develop those changes almost four (4) years ago, for my own personal use and considering they could be useful to others I did contribute them freely.

At the moment I use the fork for my own personal use and also, getting back to the changes, adapting them so that they can be merged in the latest development tree can be time consuming and it doesn't directly provide any benefit to me, as I am using my own fork.

So, I am wondering who is going to sponsor the eventual work, should I decide to create a rework ?

**Comment by depili** [comment]
You should know that the whole sigrok project is run by few volunteers without any financial backing, like most of the open source projects. We do not sponsor volunteers but one is still free to seek grants etc for contributing if one chooses, but that is way outside the scope of the project staff.

This is clearly not going anywhere, so closing this PR.

**Comment by gtrentalancia** [comment]
Unfortunately, circumstances have changed and at the moment I am quite busy with many other things related to my job.

So at the moment, I have no time to look for sponsorship, but if anybody has the time to find sponsorship then we might be able to re-open the merge of the rest of the patchset in the future...

Consider at the time of original development, back in 2019, the patchset has been distributed as a set of 93+6+4=103 small and independent patches through the official sigrok-devel@lists.sourceforge.net mailing list.

Eventually something went wrong during its review, in the sense that my set of contributed patches might have been partly mishandled or misreviewed, resulting in the mistake of not being taken all up at the time when things were fresh and I had time to spare on it.

I hope this clarifies the matter.

**Comment by gtrentalancia** [comment]
However, if you are looking at the individual patches, then you should look at the github.com forks (libsigrok, sigrok-cli and pulseview) available here: https://github.com/gtrentalancia

The three forks on github are split into several individual patches, in order to introduce all changes as listed at http://sigrok-fork.trentalancia.com (please ignore the tarballs, just look at the description of individual changes, some of them are already merged)...

So from the three github forks it is extremely easy to merge the remaining changes !

I hope it helps.

**Pull request closed without merging**
